settings:
  title: 'Status Page'
  url: 'https://status.cf-testing.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: davidtofan-com
    name: davidtofan.com
    description: 'Personal website and blog.'
    url: 'https://davidtofan.com/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
    
  - id: davidjktofan-com
    name: davidjktofan.com
    description: 'Personal dashboard and overview of profiles, projects, and more.'
    url: 'https://davidjktofan.com/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: cf-testing-com
    name: Cloudflare Playground
    description: 'A playground and overview on Cloudflare security, performance, and serverless solutions, all of which help build a better Internet.'
    url: 'https://www.cf-testing.com/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: automatic-demo-com
    name: automatic-demo.com
    description: 'A playground and overview on Cloudflare security, performance, and serverless solutions, all of which help build a better Internet.'
    url: 'https://automatic-demo.com/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: company-research-io
    name: company-research.io
    description: 'Get a brief overview on public websites and create a comprehensive centralized report on the most relevant information.'
    url: 'https://company-research.io/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: cyberscoops-io
    name: cyberscoops.io
    description: 'Learn how to navigate the Internet in a secure and private way.'
    url: 'https://cyberscoops.io/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false

  - id: sasecloudmap-com
    name: sasecloudmap.com
    description: 'An Interactive Map of Data Center Locations of Top SASE Providers.'
    url: 'https://sasecloudmap.com/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: mihaitofan-com
    name: mihaitofan.com
    description: 'The Moment Trainer is your complete and constant companion. Exercising is the prerequisite for a good life full of joy.'
    url: 'https://www.mihaitofan.co/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: andabike-com
    name: andabike.com
    description: 'We organize bike tours in Novo Sancti Petri and Chiclana, Spain, so that you can enjoy the STREETSTEPPER to the fullest.'
    url: 'https://andabike.com/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: david-couldnt-com
    name: david.couldnt.care
    description: 'David could not care at all.'
    url: 'https://david.couldnt.care/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true